[package]
name = "ffts"
version = "0.1.0"
edition = "2024"

[dependencies]
num = "0.4"
num-complex = "0.4"
rustfft = "*"
wide = "*"
metal = { version = "0.32", optional = true }
amx = { git = "https://github.com/garbagetrash/amx-rs.git", optional = true }
